# This file is managed by ServiceBot plugin - Semaphore. The content in this file is created using a common
# template and configurations in service.yml.
# Modifications in this file will be overwritten by generated content in the nightly run.
# For more information, please refer to the page:
# https://confluentinc.atlassian.net/wiki/spaces/Foundations/pages/2871296194/Add+SemaphoreCI
apiVersion: v1alpha
kind: Project
metadata:
  name: kafka
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/kafka.git
    run_on:
    - branches
    - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
      - path: .semaphore/semaphore.yml
        level: pipeline
    whitelist:
      branches:
      - 2.3
      - 2.4
      - 2.5
      - 2.6
      - 2.7
      - 2.8
      - 3.0
      - 3.1
      - 3.2
      - 3.3
      - 3.4
      - 3.5
      - 3.6
      - 3.7
      - trunk
      - master
  custom_permissions: true
  debug_permissions:
  - empty
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  attach_permissions:
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
